### ISSUE TITLE
Can I do the automatic install with Ubuntu 16.04.5 x64?

### ISSUE THREAD

**Issue by suitup020** [cryptosharks131/Polis#1]
Get a an error message that I am not running 16.04..

**Comment by cryptosharks131** [comment]
The dependencies are set for Ubuntu 16.04.  If you would like to try another version of ubuntu, open the script after download and change the following line before running the script.

https://github.com/cryptosharks131/Polis/blob/master/polis_install.sh#L213

Remove this if statement completely or change the version number to match the one you would like to try.

**Comment by cryptosharks131** [comment]
The dependencies are set for Ubuntu 16.04.  If you would like to try another version of ubuntu, open the script after download and change the following line before running the script.

https://github.com/cryptosharks131/Polis/blob/master/polis_install.sh#L213

Remove this if statement completely or change the version number to match the one you would like to try.
